name: Build and deploy Node.js app to Azure Web App - blogsiteForDp1

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Install server dependencies
        run: npm install
        working-directory: ./server

      - name: Install client dependencies
        run: npm install
        working-directory: ./client

      - name: Build client
        run: |
          echo "CI='' >> disabling eslint warnings as errors"
          CI='' npm run build --if-present
        working-directory: ./client

      # Optional: build server if needed
      - name: Build server
        run: npm run build --if-present
        working-directory: ./server

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_142C98EB955B4099B39741AFA912A771 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_884C45C46CA74C748AED8C763D44526B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_630EF4EF3BD24F8E8C7056D9D323C147 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: "blogsiteForDp1"
          slot-name: "Production"
          package: .
